# Copyright (C) 2017 Romain Perier
# Copyright (C) 2017 Eddie Cai
# Released under the MIT license (see COPYING.MIT for the terms)

require recipes-kernel/linux/linux-yocto.inc

FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"

SRC_URI = "git://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git"
SRC_URI += " \
file://defconfig \
file://rk3288-tinkerboard.dts \
file://rk3288-palacio.dts \
"

# FROMLIST PATCH
SRC_URI += " \
file://0000-Add-MALI-driver-r17p0-01rel0.patch \
file://0001-Midgard-daptation-to-Linux-4.10.0-rcX-signatures.patch \
file://0001-Readaptation-of-Rockchip-DRM-patches-provided-by-ARM.patch \
file://0002-Integrate-the-Mali-GPU-address-to-the-rk3288-and-rk3.patch \
file://0002-UMP-Adapt-get_user_pages-calls.patch \
file://0003-Post-Mali-Kernel-device-drivers-modifications.patch \
file://0003-Renamed-Kernel-DMA-Fence-structures-and-functions.patch \
file://0004-Few-modifications-after-v4.11-headers-and-signatures.patch \
file://0004-Post-Mali-UMP-integration.patch \
file://0005-Using-the-new-header-on-4.12-kernels-for-copy_-_user.patch \
file://0009-clk-rockchip-add-all-known-operating-points-to-the-a.patch \
file://0011-arm-dts-Adding-and-enabling-VPU-services-addresses-f.patch \
file://0012-Export-rockchip_pmu_set_idle_request-for-out-of-tree.patch \
file://0013-clk-rockchip-rk3288-prefer-vdpu-for-vcodec-clock-sou.patch \
file://0014-ARMbian-RK3288-DTSI-changes.patch \
file://0019-The-ASUS-Tinkerboard-reboot-patch.patch \
file://0000-v5-1-2-doc-cx2092x-Add-DT-bingings-doc-for-CX2092X-DSP.patch \
file://0000-v5-2-2-ASoC-Add-support-for-Conexant-CX2092X-DSP.patch \
file://v8-1-3-dt-bindings-display-Add-Document-for-Rockchip-Soc-LVDS.patch \
file://v8-2-3-ARM-dts-Add-LVDS-info-for-rk3288.patch \
file://v8-3-3-drm-rockchip-Add-support-for-Rockchip-Soc-LVDS.patch \
"

SRCREV = "v4.12"
LINUX_VERSION = "4.12"
# Override local version in order to use the one generated by linux build system
# And not "yocto-standard"
LINUX_VERSION_EXTENSION = ""
PR = "r1"
PV = "${LINUX_VERSION}"

# Include only supported boards for now
COMPATIBLE_MACHINE = "(palacio-rk3288)"

KCONFIG_MODE = "--alldefconfig"

do_copy_dts() {
	cp ${WORKDIR}/*.dts ${WORKDIR}/git/arch/${ARCH}/boot/dts/
}

do_unpack_append() {
    bb.build.exec_func('do_copy_dts', d)
}
